# Generated by Django 4.1.9 on 2023-08-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("message", models.CharField(blank=True, max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name="Custom_User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("profile_pic", models.ImageField(blank=True, upload_to="media/")),
                ("is_premium", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("content", models.TextField(null=True)),
                ("image", models.ImageField(blank=True, upload_to="blog/")),
                ("code", models.CharField(max_length=1000, null=True)),
                ("date_posted", models.DateField(auto_now_add=True)),
                ("time_posted", models.TimeField(auto_now_add=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        related_name="liked_blogs", to="authentication.custom_user"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.custom_user",
                    ),
                ),
            ],
        ),
    ]
